apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-kubernetes
  namespace: admin3
spec:
  releaseName: hello-kubernetes
  chart:
    spec:
      chart: deploy/helm/hello-kubernetes
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: hello-kubernetes-charts
        namespace: flux-system
  interval: 5m
  values:
    service:
      type: ClusterIP