apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin4
  namespace: flux-system
spec:
  postBuild:
    substitute:
      WORKLOAD_IDENTITY_ID: "6de71718-7f94-41f5-a8cc-c212ee70abfa"